### ISSUE TITLE
Include examples in the module

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/DynamicTitle#3]
I'd like to have the Examples included in the published module.

**Comment by mdgrs-mei** [comment]
The purpose is to make it easy for the user who installed the module to play the examples easily, correct? 

Let me move the Examples directly under the module directly and tweak the the Import-Module code in the examples.

**Comment by mdgrs-mei** [comment]
Nice idea. I will add `Start-DTExample` and `Get-DTExampleLocation`.

**Comment by mdgrs-mei** [comment]
v0.3.0 has been released to the gallery. It includes Examples directory and the new functions for the examples:

https://github.com/mdgrs-mei/DynamicTitle#examples
