### ISSUE TITLE
Add Discussions for user contributions

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/DynamicTitle#4]
I think there is a lot of opportunity for this module. I'd love to see you open up the Discussion feature and provide a place for users to contribute their examples and code.

**Comment by mdgrs-mei** [comment]
Thank you for the suggestion, and.. let's do it!

It's my first time using the Discussion feature but I'll see how it goes.

**Comment by jdhitsolutions** [comment]
I've added the first contribution.

**Comment by mdgrs-mei** [comment]
Thank you! 

Once I've sorted out the example structure, I might ask you to submit PRs if you don't mind.
