### ISSUE TITLE
Display full title with no scrolling

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/DynamicTitle#9]
I've been testing this in a legacy PowerShell console. It works as expected. However, I want to display the entire dynamic title with no scrolling. It looks like the code has a pre-defined title width. My script creates a long string which I get a glimpse of before it gets shortened. I want to be able to display something like this with no scrolling.

![image](https://user-images.githubusercontent.com/12089920/227618210-09ea077a-8d48-461f-90e1-acde23fb489b.png)

Or may be the traditional Windows console isn't supported.

**Comment by jdhitsolutions** [comment]
I can set a static title with no problem.

```powershell
start-dttitle {'📆 Mar 24 14:55:14 ⛅️ +39°F - 🔥CPU:1.2% 💽16.53% free 💻57.83% free'}
```

**Comment by mdgrs-mei** [comment]
What happens if you remove the `HorizontalScrollFrameWidth` parameter? The default behavior without the `HorizontalScrollFrameWidth` parameter is no scrolling and no width limit in the code.

I removed the FrameWidth parameter in your StatusBar2 example (and added some words just in case). It's seems to be working on the legacy console.

![image](https://user-images.githubusercontent.com/81177095/227715755-5164c37d-34f1-4bc7-b527-87cf631b0701.png)

**Comment by jdhitsolutions** [comment]
This is odd then. Here's the code I'm running.

```powershell
#requires -module DynamicTitle

#no scrolling. Use in legacy consoles.

function StartDTStatusBar3 {
    $modulePath = (Get-Module DynamicTitle).Path

    #update every 30 minutes
    $weatherJob = Start-DTJobBackgroundThreadTimer -ScriptBlock {
        $weather = Invoke-RestMethod https://wttr.in/?format="%c%t\n"
        $weather
    } -IntervalMilliseconds 1800000

    #update every 2 seconds
    $systemInfoJob = Start-DTJobBackgroundThreadTimer -ScriptBlock {
        $cpuUsage = (Get-Counter -Counter '\Processor(_Total)\% Processor Time').CounterSamples.CookedValue
        $cpuUsage
    } -IntervalMilliseconds 2000

    #test every 15 minutes
    $DiskInfoJob = Start-DTJobBackgroundThreadTimer -ScriptBlock {
        $c = Get-CimInstance -ClassName Win32_LogicalDisk -Filter 'DeviceID = "C:"' -Property Size, FreeSpace
        ($c.FreeSpace / $c.size)
    } -IntervalMilliseconds 900000

    #update every 30 seconds
    $memInfoJob = Start-DTJobBackgroundThreadTimer -ScriptBlock {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem -Property FreePhysicalMemory, TotalVisibleMemorySize
        ($os.FreePhysicalMemory / $os.TotalVisibleMemorySize)
    } -IntervalMilliseconds 30000

    $initializationScript = {
        param ($modulePath)
        Import-Module $modulePath
    }

    $scriptBlock = {
        param($weatherJob, $systemInfoJob, $diskInfoJob, $memInfoJob)

        $weather = Get-DTJobLatestOutput $weatherJob
        $cpuUsage = Get-DTJobLatestOutput $systemInfoJob
        $diskInfo = Get-DTJobLatestOutput $DiskInfoJob
        $memInfo = Get-DTJobLatestOutput $memInfoJob
        $date = Get-Date -Format 'MMM dd HH:mm:ss'

    '📆{0} {1} 🔥CPU:{2:f1}% 💽{3:p2} free 💻{4:p2} free' -f $date, $weather, [double]$cpuUsage, [double]$DiskInfo, [double]$Meminfo

    }

    $params = @{
        ScriptBlock                          = $scriptBlock
        ArgumentList                         = $weatherJob, $systemInfoJob, $DiskInfoJob, $memInfoJob
        InitializationScript                 = $initializationScript
        InitializationArgumentList           = $modulePath
    }

    Start-DTTitle @params
}

StartDTStatusBar3
```
Using a PowerShell 7 console, not Windows Terminal.

![image](https://user-images.githubusercontent.com/12089920/227971918-daf30524-f024-47fb-a020-1bbf8f72abfc.png)

I get a flash of the full status bar then it gets cut short to what you see in the screenshot. This is on Windows 11 Pro.

**Comment by jdhitsolutions** [comment]
The script works as expected in Windows Terminal. This is an issue in the legacy console and may be a limitation, which is fine. This becomes a documentation update to let the user know your module doesn't work in the legacy console.

**Comment by mdgrs-mei** [comment]
Finally reproduced!

I noticed that when printing the WindowTitle, there is a new line after the weather. Probably my weather example is doing something bad here.

![image](https://user-images.githubusercontent.com/81177095/227982220-4f89eed6-3591-409a-afda-bb2f70383d3b.png)

**Comment by jdhitsolutions** [comment]
I noticed that earlier but thought it was something else. Using this fixes the problem.

```powershell
    $weatherJob = Start-DTJobBackgroundThreadTimer -ScriptBlock {
        $weather = Invoke-RestMethod https://wttr.in/?format="%c%t\n"
        $weather.Trim()
    } -IntervalMilliseconds 1800000
```

**Comment by jdhitsolutions** [comment]
I think this can be closed now that we know that issue is unrelated to the module command.
